Develop lab1
mshnschnko/os-labs pull request #1
Opened 2023-10-26 11:23 UTC by mshnschnko

2023-10-27 21:31 UTC, DariaWelt requested changes
В целом всё работает, но если в конфиге неверные пути, то демон закрывается без какого-либо сообщения в лог.

В остальном всё хорошо.

2023-10-28 10:17 UTC, mshnschnko commented
Добавил проверку на существование конфиг файла, перенес pid файл в /var/run.

Насчет _если в конфиге неверные пути, то демон закрывается без какого-либо сообщения в лог_. Ломалось, вероятно, в строке `for (const auto &file : fs::directory_iterator(pair.first))` при попытке итерироваться по несуществующей директории. У меня было две идеи исправления: 
1. При прочтении конфига не включать в список директорий те, которых не существует. Но тогда после создания этой директории требуется принудительное перепрочтение конфиг файла, чтобы демон стал ее тоже проверять.
2. Включить в список каталогов всё, что указано в конфиге, а проверять существование перед удалением. Тогда после создания папки, которая есть в конфиге, но которой не было раньше, ничего перечитывать не нужно, а демон будет очищать ее (при условии отсутствия ignfile) без наших дополнительных действий.

Я выбрал второй вариант

2023-10-28 12:15 UTC, DariaWelt approved these changes
Работа зачтена.

2023-10-28 12:15 UTC, DariaWelt commented on lab1/deleter_daemon/Deleter.cpp
> +        syslog(LOG_NOTICE, "Config file does not exist. Daemon terminated");
Лучше такие вещи писать в LOG_ERROR.

2023-10-28 12:16 UTC, merged