Develop lab2
mshnschnko/os-labs pull request #2
Opened 2023-11-27 23:39 UTC by mshnschnko

Программа компилируется. Работает для соединений shm и fifo. Для mmap решить проблему так и не удалось. В соответствующем .cpp файле оставил в закомментированной части свои попытки заставить хоста и клиента пользоваться одной областью памяти. Если среди них есть какая-то здравая, то прошу указать на нее. То, что я оставил сейчас в незакомментированном виде выделяет два разных сегмента памяти, из-за чего хост постоянно считывает число 0. Есть предположение о том, чтобы передавать указатель на выделенную память через семафор, как я делаю это со `state`, но тогда код будет по сути зависеть от типа соединения и для mmap работать не так, как для остальных, поскольку для двух других передача указателя не требуется. Всё остальное работает как предполагается.

2023-12-02 20:49 UTC, DariaWelt requested changes
программа рабочая, есть два небольших замечания по процессу сборки

2023-12-02 20:49 UTC, DariaWelt commented on lab2/build.sh
> +cp $BUILD_DIR/host_fifo $BIN_DIR
При копировании можно использовать * для переноса нескольких файлов. У вас все exe файлы хоста начинаются с host, а все файлы клиента с client

2023-12-02 20:49 UTC, DariaWelt commented on lab2/build.sh
> +BIN_DIR="bin"
файлы должны записываться в директорию лабы, пожалуйста, исправьте путь до BIN_DIR

2023-12-03 11:25 UTC, mshnschnko commented
Заменил mmap на mq, как мы решили в обсуждении в телеграме.

2023-12-09 12:05 UTC, DariaWelt approved these changes
работа зачтена

2023-12-09 12:05 UTC, merged