Develop lab3 Анищенко Михаил
mshnschnko/os-labs pull request #3
Opened 2023-12-16 10:42 UTC by mshnschnko

Делал только одно соединение (множество с тонкой синхронизацией)

2023-12-19 08:51 UTC, DariaWelt requested changes
вот такой тест провалился:
```
(base) daria@daria-0-1:~/os_labs/mshnschnko/lab3$ ./lab3 config2.txt 
Count of writers: 5, count of writers size 10
Count of readers: 3, count of readers size 10
Count of tests: 1133767216

Fine-Grained Set:
Writing functional test	n_writers: 5	size: 10	result: success
Reading functional test	n_readers: 3	size: 10	result: success
General functional test	size for reading: 10	size for writing: 10
n_readers: 1	n_writers: 3	reading result: success	writing result: fail (miss value)
n_readers: 2	n_writers: 2	reading result: success	writing result: success
n_readers: 3	n_writers: 1	reading result: success	writing result: fail (miss value)
    
^C
(base) daria@daria-0-1:~/os_labs/mshnschnko/lab3$ cat config2.txt 
5 10
3 10

```
и программа зависла, так что выходила я через ctrl+c

2023-12-20 06:49 UTC, mshnschnko commented
Судя по выводу в консоль, Вы не указали количество тестов для вычисления среднего времени работы. Я добавил проверку на некорректность аргументов конфиг файла.

Насчет зависшей программы: думаю, она не зависла, а из-за неуказанного числа тестов (либо если Вы все-таки указали такое большое число, а именно 1133767216), просто долго выполняется. Например, у меня при 10 тестах по 5000 запией получается среднее время работы (чтение + запись) 400-500 мс. При 10 записях и 10 тестах вся программа выполняется немного меньше, чем за секунду, а среднее время 4 мс. При 1133767216 тестах можно ожидать выполнение в течение нескольких часов, если навскидку. Поэтому я добавил таймаут для выполнения таких тестов.

2023-12-22 22:40 UTC, mshnschnko commented
Итак, почему валился тест. Когда я провожу общий тест, я одновременно пишу и удаляю данные. Мною был установлен seed, чтобы в целях проверки случайные данные не были случайными и можно было с их помощью проверять работоспособность кода. Чтобы проверить правильность чтения я делал, как написано в условии: удалял элемент и выставлял флаг 1 в "проверочный массив". При этом мы не можем контролировать порядок исполнения методов, поэтому возникала следующая ошибка. Я заносил данные от 1 до n-1 во множество. Затем, запуская запись и чтение одновременно (и их проверки как следствие), один из возможных сценариев был таким: в случайно сгенерированном ряде были числа от 1 до n-1, т.е. повторения с первым массивом. И если последовательность действий случалась такая: добавление, удаление, проверка записи через contains, то тест проваливался, хотя фактически все было сделано верно. Чтобы не попадать в ситуации. Чтобы не попадать в ситуации, когда мы не можем проверить правильность выполнения программы, я переделал немного генерацию данных. Теперь массив для проверки чтения и массив для записи не имеют пересекающихся элементов. Таким образом, мы можем проверить, что все элементы первого массива были считаны и обозначены флагом в проверочном массиве checkArr, а также, что все элементы второго массива (случайного) были добавлены во множество (проверка через contains). При этом все еще остается параллельное чтение и запись во множество.

2023-12-22 22:53 UTC, mshnschnko commented
Был косяк с пределами для генерации случайного массива. Теперь массивы не пересекаются, как я сказал в прошлом комментарии

2023-12-24 07:54 UTC, DariaWelt reviewed
Непонятные результаты по времени
<pre>
Count of writers: 3, count of writers size 10
Count of readers: 5, count of readers size 100
Count of tests: 15
Timeout for performance test: 7 sec

Fine-Grained Set:
Writing functional test	n_writers: 3	size: 10	result: success
Reading functional test	n_readers: 5	size: 100	result: success
General functional test	size for reading: 100	size for writing: 10
n_readers: 1	n_writers: 1	reading result: success	writing result: success

Writing performance test	n_writers: 3	size: 10	<b>time: 0 ms</b>
Reading performance test	n_readers: 3	size: 100	<b>time: 0 ms</b>
General performance test	size for reading: 100	size for writing: 10
n_readers: 1	n_writers: 1	time: 0 ms
</pre>

2023-12-24 07:54 UTC, DariaWelt commented on lab3/tester.h
> +      for (int j = 0; j < numOfTests; ++j, ++num_of_performed_tests) {
непонятно зачем j, если есть num_of_performed_tests

2023-12-24 10:21 UTC, mshnschnko commented
Увеличил точность подсчета времени до микросекунд. Для более понятного вывода сделал перевод в миллисекунды, если требуется. Чтобы не было нуля в выводе в консоли. И убрал лишние счетчики.

2023-12-24 11:33 UTC, DariaWelt approved these changes
Работа зачтена

2023-12-24 11:33 UTC, merged